services:
  osrm-walking:
    image: osrm/osrm-backend:latest
    container_name: nazaroute-osrm-walking
    command: osrm-routed --algorithm mld /data/granada-foot.osrm
    volumes:
      - ../osrm/walking:/data:ro
    ports:
      - "5001:5000"
