events {}

http {
  server {
    listen 443 ssl;

    ssl_certificate     /etc/ssl/cert.pem;
    ssl_certificate_key /etc/ssl/key.pem;

    location / {
      proxy_pass http://osrm-walking:5000;
      proxy_set_header Host $host;
    }
  }
}
